# Site settings, modified from Karpathy's blog: https://github.com/karpathy/karpathy.github.io
title: Mind Repository
email: 
description: "Mind Repository"
baseurl: ""
url: "http://yuweilin.github.io"
github_username: yuweilin

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
    input: GFM
    auto_ids: true
    syntax_highlighter: rouge
